//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaquinaDeCafe.src.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorsMensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorsMensagem() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaquinaDeCafe.src.Resources.ErrorsMensagem", typeof(ErrorsMensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A descrição deve ter pelo menos 5 caracteres..
        /// </summary>
        public static string CafeDescricaoMinima {
            get {
                return ResourceManager.GetString("CafeDescricaoMinima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A descrição é obrigatória..
        /// </summary>
        public static string cafeDescricaoObrigatorio {
            get {
                return ResourceManager.GetString("cafeDescricaoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A descrição do café deve ter pelo menos 5 caracteres..
        /// </summary>
        public static string cafeDescricaoTamanhoMinimo {
            get {
                return ResourceManager.GetString("cafeDescricaoTamanhoMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Café não encontrado..
        /// </summary>
        public static string CafeNaoEncontrado {
            get {
                return ResourceManager.GetString("CafeNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do café é obrigatório..
        /// </summary>
        public static string CafeNomeObrigatorio {
            get {
                return ResourceManager.GetString("CafeNomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O preço deve ser maior que zero..
        /// </summary>
        public static string CafePrecoMaiorQueZero {
            get {
                return ResourceManager.GetString("CafePrecoMaiorQueZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Forma de preparo não encontrado..
        /// </summary>
        public static string FormaPreparoNaoEncontrado {
            get {
                return ResourceManager.GetString("FormaPreparoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome da forma de preparo é obrigatório..
        /// </summary>
        public static string FormaPreparoNomeObrigatorio {
            get {
                return ResourceManager.GetString("FormaPreparoNomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O tempo de preparo deve ser maior que zero..
        /// </summary>
        public static string FormaPreparoTempoInvalido {
            get {
                return ResourceManager.GetString("FormaPreparoTempoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do ingrediente adicional é obrigatório..
        /// </summary>
        public static string IngredienteAdicionalNomeObrigatorio {
            get {
                return ResourceManager.GetString("IngredienteAdicionalNomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor extra deve ser maior ou igual a zero..
        /// </summary>
        public static string IngredienteAdicionalValorInvalido {
            get {
                return ResourceManager.GetString("IngredienteAdicionalValorInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome não pode ser vazio..
        /// </summary>
        public static string IngredienteNomeObrigatorio {
            get {
                return ResourceManager.GetString("IngredienteNomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor extra deve ser maior que zero..
        /// </summary>
        public static string IngredienteValorExtraInvalido {
            get {
                return ResourceManager.GetString("IngredienteValorExtraInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário selecionar um café..
        /// </summary>
        public static string PedidoCafeObrigatorio {
            get {
                return ResourceManager.GetString("PedidoCafeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário selecionar uma forma de preparo..
        /// </summary>
        public static string PedidoFormaPreparoObrigatoria {
            get {
                return ResourceManager.GetString("PedidoFormaPreparoObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O produto selecionado está indisponível..
        /// </summary>
        public static string PedidoProdutoIndisponivel {
            get {
                return ResourceManager.GetString("PedidoProdutoIndisponivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A quantidade deve ser maior que zero..
        /// </summary>
        public static string PedidoQuantidadeInvalida {
            get {
                return ResourceManager.GetString("PedidoQuantidadeInvalida", resourceCulture);
            }
        }
    }
}
