// <auto-generated />
using System;
using MaquinaDeCafe.src.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MaquinaDeCafe.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250619211302_InitialCatalog")]
    partial class InitialCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.AvaliacaoCafe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Atendimento")
                        .HasColumnType("integer");

                    b.Property<Guid>("CafeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estrelas")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CafeId");

                    b.ToTable("Avaliacoes_cafe", (string)null);
                });

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.Cafe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Categoria")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TempoPreparoSegundos")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Cafes", (string)null);
                });

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.IngredienteAdicional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ValorExtra")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("IngredientesAdicionais", (string)null);
                });

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.PedidoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CafeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<Guid>("TamanhoXicaraId")
                        .HasColumnType("uuid");

                    b.Property<int>("TempoPreparoSegundos")
                        .HasColumnType("integer");

                    b.Property<string>("TipoAcucar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoLeite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CafeId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("TamanhoXicaraId");

                    b.ToTable("PedidoItens", (string)null);
                });

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.PedidoItemIngredienteAdicional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IngredienteAdicionalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PedidoItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IngredienteAdicionalId");

                    b.HasIndex("PedidoItemId");

                    b.ToTable("PedidoItemIngredienteAdicional");
                });

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.TamanhoXicara", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CafeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Ml")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CafeId");

                    b.ToTable("TamanhosXicara", (string)null);
                });

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.AvaliacaoCafe", b =>
                {
                    b.HasOne("MaquinaDeCafe.src.Models.Entities.Cafe", "Cafe")
                        .WithMany("AvaliacoesCafe")
                        .HasForeignKey("CafeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cafe");
                });

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.PedidoItem", b =>
                {
                    b.HasOne("MaquinaDeCafe.src.Models.Entities.Cafe", "Cafe")
                        .WithMany("PedidoItens")
                        .HasForeignKey("CafeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MaquinaDeCafe.src.Models.Entities.Pedido", "Pedido")
                        .WithMany("PedidoItens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaquinaDeCafe.src.Models.Entities.TamanhoXicara", "TamanhoXicara")
                        .WithMany("PedidoItens")
                        .HasForeignKey("TamanhoXicaraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cafe");

                    b.Navigation("Pedido");

                    b.Navigation("TamanhoXicara");
                });

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.PedidoItemIngredienteAdicional", b =>
                {
                    b.HasOne("MaquinaDeCafe.src.Models.Entities.IngredienteAdicional", "IngredienteAdicional")
                        .WithMany("PedidoItemIngredientes")
                        .HasForeignKey("IngredienteAdicionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaquinaDeCafe.src.Models.Entities.PedidoItem", "PedidoItem")
                        .WithMany("PedidoItemIngredientes")
                        .HasForeignKey("PedidoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredienteAdicional");

                    b.Navigation("PedidoItem");
                });

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.TamanhoXicara", b =>
                {
                    b.HasOne("MaquinaDeCafe.src.Models.Entities.Cafe", "Cafe")
                        .WithMany("TamanhosXicara")
                        .HasForeignKey("CafeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cafe");
                });

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.Cafe", b =>
                {
                    b.Navigation("AvaliacoesCafe");

                    b.Navigation("PedidoItens");

                    b.Navigation("TamanhosXicara");
                });

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.IngredienteAdicional", b =>
                {
                    b.Navigation("PedidoItemIngredientes");
                });

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.Pedido", b =>
                {
                    b.Navigation("PedidoItens");
                });

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.PedidoItem", b =>
                {
                    b.Navigation("PedidoItemIngredientes");
                });

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.TamanhoXicara", b =>
                {
                    b.Navigation("PedidoItens");
                });
#pragma warning restore 612, 618
        }
    }
}
