// <auto-generated />
using System;
using MaquinaDeCafe.src.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MaquinaDeCafe.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250504175837_intialCatalog")]
    partial class intialCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.Cafe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.ToTable("Cafes", (string)null);
                });

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.FormaPreparo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TempoPreparoMinutos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FormasPreparo", (string)null);
                });

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.IngredienteAdicional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("ValorExtra")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("IngredientesAdicionais", (string)null);
                });

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormaPreparoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FormaPreparoId1")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FormaPreparoId");

                    b.HasIndex("FormaPreparoId1");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.PedidoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CafeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<string>("TamanhoXicara")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoAcucar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoLeite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CafeId");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoItens", (string)null);
                });

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.PedidoItemIngredienteAdicional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredienteAdicionalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PedidoItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IngredienteAdicionalId");

                    b.HasIndex("PedidoItemId");

                    b.ToTable("PedidoItemIngredienteAdicional", (string)null);
                });

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.Pedido", b =>
                {
                    b.HasOne("MaquinaDeCafe.src.Models.Entities.FormaPreparo", "FormaPreparo")
                        .WithMany()
                        .HasForeignKey("FormaPreparoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MaquinaDeCafe.src.Models.Entities.FormaPreparo", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("FormaPreparoId1");

                    b.Navigation("FormaPreparo");
                });

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.PedidoItem", b =>
                {
                    b.HasOne("MaquinaDeCafe.src.Models.Entities.Cafe", "Cafe")
                        .WithMany("PedidoItens")
                        .HasForeignKey("CafeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MaquinaDeCafe.src.Models.Entities.Pedido", "Pedido")
                        .WithMany("PedidoItens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cafe");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.PedidoItemIngredienteAdicional", b =>
                {
                    b.HasOne("MaquinaDeCafe.src.Models.Entities.IngredienteAdicional", "IngredienteAdicional")
                        .WithMany()
                        .HasForeignKey("IngredienteAdicionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaquinaDeCafe.src.Models.Entities.PedidoItem", "PedidoItem")
                        .WithMany()
                        .HasForeignKey("PedidoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredienteAdicional");

                    b.Navigation("PedidoItem");
                });

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.Cafe", b =>
                {
                    b.Navigation("PedidoItens");
                });

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.FormaPreparo", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("MaquinaDeCafe.src.Models.Entities.Pedido", b =>
                {
                    b.Navigation("PedidoItens");
                });
#pragma warning restore 612, 618
        }
    }
}
